describe('overall upload workflow', () => {

    beforeEach(() => {
        const test_username = `test_${Math.random().toString(36).slice(-4)}`
        const test_password = Math.random().toString(36).slice(-8)
        const test_email = `${test_username}@weed-ai.com`
        cy.visit('http://localhost/upload', {failOnStatusCode: false})
        cy.register(test_username, test_email, test_password)
        cy.login(test_username, test_password)
    })

    it('Test Weedcoco Upload', () => {
        cy.findAllByText(/^Select annotation format$/).should('have.length', 1).type('weedcoco{enter}')
        cy.clickText(/^Begin upload$/)
        cy.get('.dzu-input').attachFile('test_weedcoco/weedcoco.json')
        cy.clickText(/^Next$/)
        cy.get('div.fileContainer > input').attachFile('test_weedcoco/images/001_image.png')
        cy.clickText(/^Submit$/)
    })

    it('Test Coco Upload', () => {
        cy.findByText(/^Select annotation format$/).click()
        cy.findByText("COCO").click()
        cy.clickText(/^Begin upload$/)
        cy.get('.dzu-input').attachFile('test_coco/coco.json')
        cy.clickText(/^Next$/)
        cy.findByText("crop").type('weed{enter}')
        cy.findByDisplayValue(/^UNSPECIFIED$/).click().clear().type('rapistrum rugosum{enter}')
        cy.clickText(/^Apply$/)
        cy.clickText(/^Next$/)
        cy.clickText(/^Upload and Download Form Contents$/)
        cy.get('.dzu-input').attachFile('test_coco/agcontext.json')
        cy.wait(10000)
        cy.clickText(/^Set Form$/)
        cy.clickText(/^Next$/)
        cy.clickText(/^Upload and Download Form Contents$/)
        cy.get('.dzu-input').attachFile('test_coco/metadata.json')
        cy.wait(10000)
        cy.clickText(/^Set Form$/)
        cy.clickText(/^Next$/)
        cy.get('div.fileContainer > input').attachFile('test_coco/images/002_image.png')
        cy.clickText(/^Submit$/)
    })

    it('Test Voc Upload', () => {
        cy.findByText(/^Select annotation format$/).click()
        cy.findByText("VOC").click()
        cy.clickText(/^Begin upload$/)
        cy.get('.dzu-input').attachFile('test_voc/voc/resizeC1_PLOT_20190728_175852.xml')
        cy.get('.dzu-input').attachFile('test_voc/voc/resizeC1_PLOT_20190728_180135.xml')
        cy.get('.dzu-submitButton').click()
        cy.clickText(/^Next$/)
        cy.clickText(/^Apply$/)
        cy.clickText(/^Next$/)
        cy.clickText(/^Upload and Download Form Contents$/)
        cy.get('.dzu-input').attachFile('test_voc/agcontext.json')
        cy.wait(10000)
        cy.clickText(/^Set Form$/)
        cy.clickText(/^Next$/)
        cy.clickText(/^Upload and Download Form Contents$/)
        cy.get('.dzu-input').attachFile('test_voc/metadata.json')
        cy.wait(10000)
        cy.clickText(/^Set Form$/)
        cy.clickText(/^Next$/)
        cy.get('div.fileContainer > input').attachFile('test_voc/images/resizeC1_PLOT_20190728_175852.jpg')
        cy.get('div.fileContainer > input').attachFile('test_voc/images/resizeC1_PLOT_20190728_180135.jpg')
        cy.clickText(/^Submit$/)
    })

    afterEach(() => {
        cy.findAllByText(/^Log out$/).should('have.length', 1).click()
    })
})