# Generated by Django 2.2.13 on 2020-12-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weedid", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataset",
            name="upload_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
