# Generated by Django 2.2.13 on 2020-12-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weedid", "0002_auto_20201204_0148"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataset",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("N", "None"),
                    ("P", "Processing"),
                    ("I", "Incomplete"),
                    ("AR", "Awaiting Review"),
                    ("F", "Failed"),
                    ("C", "Complete"),
                ],
                default="N",
                max_length=2,
            ),
        ),
    ]
