# Generated by Django 2.2.13 on 2021-01-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weedid", "0004_dataset_upload_status_details"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataset",
            old_name="upload_agcontext",
            new_name="agcontext",
        ),
        migrations.RenameField(
            model_name="dataset",
            old_name="upload_annotation_type",
            new_name="annotation_type",
        ),
        migrations.RenameField(
            model_name="dataset",
            old_name="upload_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="dataset",
            old_name="upload_status",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="dataset",
            old_name="upload_status_details",
            new_name="status_details",
        ),
        migrations.RenameField(
            model_name="dataset",
            old_name="upload_user",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="dataset",
            name="upload_id",
            field=models.CharField(
                max_length=40, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
