# Generated by Django 2.2.13 on 2021-01-22 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weedid", "0005_auto_20210122_0334"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataset",
            old_name="annotation_type",
            new_name="annotation_format",
        ),
        migrations.RemoveField(
            model_name="weediduser",
            name="accessible_datasets",
        ),
    ]
