# Generated by Django 2.2.13 on 2021-03-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weedid", "0006_auto_20210122_0410"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataset",
            name="status_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
