name: Check search frontend

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '**'

jobs:
  check-search-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
#      - uses: satackey/action-docker-layer-caching@v0.0.11
#        continue-on-error: true
      - name: Bring system up
        env:
          MERGE_SHA: ${{ github.sha }}
        run: |
            set -x
            cd search
            mkdir -p live-data
            cat > .env <<HERE
            DJANGO_SECRET_KEY=mysecret
            POSTGRES_USER=postgres
            POSTGRES_PASSWORD=postgres
            POSTGRES_DB=weedai
            WEEDCOCO_VERSION=$MERGE_SHA
            SEND_EMAIL=False
            HERE
            cat .env
            # TODO The following could be a separate GitHub action
            docker-compose up -d --build
            sleep 1
            get_statuses() {
              docker-compose ps -q | xargs docker inspect --format '{{.State.Status}} {{if .State.Health}}{{.State.Health.Status}}{{end}} }}'
            }
            while get_statuses | grep -q starting; do sleep 1; done
            if get_statuses | grep -q -e exited -e restarting -e unhealthy; then false; fi
            curl -L http://localhost/api/warmup/
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install weedcoco library
        run: |
          pip install .
      - name: Index test data
        run: |
          bash search/scripts/index_test_images.sh
      # TODO: find syntax to run shutdown regardless of previous step outcomes
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: search
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: search/cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: search/cypress/videos
      - name: Check logs upon failure
        run: |
            cd search
            docker-compose logs --tail="all"
            docker-compose ps
        if: ${{ failure() }}
      - name: Shutdown
        run: |
            cd search
            docker-compose down
        if: ${{ always() }}
