name: Check search frontend

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '**'

jobs:
  check-search-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Bring system up
        run: |
            set -ex
            cd search
            mkdir -p live-data
            docker-compose up -d
            sleep 1
            while docker-compose ps | grep health:.starting > /dev/null; do sleep 1; done
            ! (docker-compose ps | grep -q 'elasticsearch.*Up.(unhealthy)') || (echo "Found unhealthy!" && docker-compose ps; docker-compose logs; false)
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Install weedcoco library
        run: |
          pip install .
      - name: Index test data
        run: |
          bash search/scripts/index_test_images.sh
      # TODO: find syntax to run shutdown regardless of previous step outcomes
      - name: Shutdown
        run: |
            cd search
            docker-compose down
        if: ${{ always() }}
